server:
  address: 0.0.0.0
  port: 8082

spring:
  grpc:
    server:
      port: 9082
  datasource:
    url: ${USER_DATASOURCE_URL:jdbc:postgresql://localhost:5433/user-database}
    username: ${USER_DATASOURCE_USERNAME:admin}
    password: ${USER_DATASOURCE_PASSWORD:admin}
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - info
  metrics:
    tags:
      application: user-service
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    resource-attributes:
      service.name: ars-user-service
    tracing:
      export:
        otlp:
          endpoint: ${OTLP_ENDPOINT:http://localhost:4317}
          transport: grpc
  otlp:
    metrics:
      export:
        enabled: false