server:
  address: 0.0.0.0
  port: 8082

spring:
  grpc:
    server:
      port: 9082
  datasource:
    url: jdbc:postgresql://localhost:5433/user-database
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

management:
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    resource-attributes:
      service.name: ars-user-service
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4317
          transport: grpc
  otlp:
    metrics:
      export:
        enabled: false