server:
  address: 0.0.0.0
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/auth-database
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

resilience4j:
  retry:
    instances:
      user-register:
        max-attempts: 3
        wait-duration: 500ms
      provider-register:
        max-attempts: 3
        wait-duration: 500ms


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    resource-attributes:
      service.name: ars-authenticator
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4317
          transport: grpc
  otlp:
    metrics:
      export:
        enabled: false


jwk:
  rsa:
    public: ${ARS_RSA_PUBLIC_KEY}
    private: ${ARS_RSA_PRIVATE_KEY}